### ISSUE TITLE
Исправить отображение о проверках документов

### ISSUE THREAD

**Issue by mkozhevnikov2323** [ilb/classifiercomponent#22]
Проверить и исправить логику отображения проверок и ошибок у документа в интерфейсе досье.
![image](https://github.com/ilb/classifiercomponent/assets/64350651/ced3673d-35cf-4cc1-af31-ae3c1a199e98)

**Comment by Svet14Lana** [comment]
@Barakok протестировано, сейчас так 
![image](https://github.com/ilb/classifiercomponent/assets/92314882/4a4869c3-216c-483f-9f4c-675bfcf96aa8)
